
services:
  base:
    &base
    build:
        context: .
    volumes:
      - .:/code
  langres:
    &langres
    <<: *base
    entrypoint: bash
  migrate:
    <<: *base
    entrypoint: diesel migration redo --all --database-url="langres.db"
    working_dir: /code/src-tauri
  test:
    <<: *base
    entrypoint: cargo test -- --test-threads=1
    volumes:
    - .:/code
    - cargo-target:/code/target
    working_dir: /code/src-tauri
volumes:
  cargo-target:
