
services:
  base:
    &base
    build:
        context: .
    volumes:
      - .:/code
      - cargo-target:/code/src-tauri/target
  langres:
    &langres
    <<: *base
    entrypoint: bash
  migrate:
    <<: *base
    entrypoint: diesel migration redo --all --database-url="langres.db"
    working_dir: /code/src-tauri
  shell:
    <<: *base
    entrypoint: cargo run --bin shell
    working_dir: /code/src-tauri
  lint:
    <<: *base
    entrypoint: cargo clippy
    working_dir: /code/src-tauri
  test:
    <<: *base
    entrypoint: cargo test
    working_dir: /code/src-tauri
volumes:
  cargo-target:
