version: '3'

env:
    TEST_ARGS: --test-threads=1
    RUST_DIR: src-tauri
    DOCKER_CMD: docker compose run --rm

tasks:
    # Local commands
    init:
        desc: Install requirements and prepare project to run.
        aliases:
            - install
            - setup
        cmds:
            - task init:front
            - task init:back
        silent: true

    init:front:
        desc: Install frontend requirements.
        cmds:
            - npm install
        silent: true

    init:back:
        desc: Install backend requirements.
        cmds:
            - cargo install diesel_cli
            - rustup component add clippy
        silent: true

    build:
        desc: Build and compile project.
        aliases:
            - compile
        cmds:
            - npm run tauri build
        silent: true

    dev:
        desc: Run local project.
        aliases:
            - run
            - start
            - launch
        cmds:
            - npm run tauri dev
        silent: true

    lint:
        desc: Run linter on the whole project.
        cmds:
            - task lint:front -- {{.CLI_ARGS}}
            - task lint:back -- {{.CLI_ARGS}}
        silent: true

    lint:front:
        desc: Run Eslint
        cmds:
            - npm run lint {{.CLI_ARGS}}
        silent: true

    lint:back:
        dir: '{{.RUST_DIR}}'
        desc: Run cargo clippy
        cmds:
            - cargo clippy {{.CLI_ARGS}}
        silent: true

    tests:
        dir: '{{.RUST_DIR}}'
        desc: Run tests, you can specify the path of the subset of tests to run as argument.
        aliases:
            - test
        cmds:
            - cargo test {{.CLI_ARGS}} -- {{.TEST_ARGS}} {{if ne .CLI_ARGS ""}}--nocapture{{end}}
        silent: true

    benchmark_tests:
        desc: Run tests set multiple times to check against flakies.
        dir: '{{.RUST_DIR}}'
        cmds:
            - |
                set -- {{.CLI_ARGS}}
                ITERATIONS=${1:-100}
                TEST_FILTER="$2"
                for i in $(seq 1 $ITERATIONS); do
                    printf "\rTest run $i/$ITERATIONS"
                    if [ -n "$TEST_FILTER" ]; then
                        cargo test "$TEST_FILTER" -- {{.TEST_ARGS}} --quiet || { echo -e "\nFAILED on run $i"; exit 1; }
                    else
                        cargo test -- {{.TEST_ARGS}} --quiet || { echo -e "\nFAILED on run $i"; exit 1; }
                    fi
                done
                echo -e "\nAll $ITERATIONS test runs passed successfully!"
        silent: true

    migrations:
        dir: '{{.RUST_DIR}}'
        desc: Run project's migrations
        aliases:
            - migrate
        cmds:
            - diesel migration redo --all --database-url="langres.db"
            - diesel migration redo --all --database-url="test_db.db"
        silent: true

    clear:
        dir: '{{.RUST_DIR}}'
        desc: Clear build artifacts.
        aliases:
            - clean
        cmds:
            - cargo clean
        silent: true

    todo:
        desc: Output all todos.
        aliases:
            - todos
        cmds:
            - grep -rn "TODO" ./src-tauri/src
            - grep -rn "TODO" ./src
        silent: true

    shell:
        dir: '{{.RUST_DIR}}'
        desc: Run interactive shell environment
        cmds:
            - cargo run --bin shell
        silent: true

    # Docker commands
    docker:
        desc: Run migrations through docker environment
        aliases:
            - docker-bash
        cmds:
            - docker compose run --rm langres
        silent: true

    docker-init:
        desc: Build docker environment
        aliases:
            - docker-build
        cmds:
            - docker compose build
        silent: true

    docker-migrate:
        desc: Run migrations through docker environment
        cmds:
            - docker compose run --rm migrate'
        silent: true

    docker-tests:
        desc: Run unit tests through docker environment
        aliases:
            - docker-test
        cmds:
            - docker compose run --rm test {{.CLI_ARGS}} -- {{.TEST_ARGS}} {{if ne .CLI_ARGS ""}}--nocapture{{end}}
        silent: true

    docker-lint:
        desc: Run cargo clippy through docker environment
        cmds:
            - docker compose run --rm lint
        silent: true

    docker-shell:
        desc: Run interactive shell through docker environment
        cmds:
            - docker compose run --rm shell
        silent: true
