import { IoVolumeHigh, IoVolumeMuteSharp, IoVolumeMedium, IoHome } from 'react-icons/io5';
import { RiCheckboxBlankCircleLine, RiCheckboxCircleLine, RiLandscapeFill } from 'react-icons/ri';
import { BsTrash, BsWater, BsHexagonFill } from 'react-icons/bs';
import { GrView, GrPowerReset } from 'react-icons/gr';
import { HiOutlineArrowLeft, HiOutlineArrowRight } from 'react-icons/hi2';
import { BiSolidTree } from 'react-icons/bi';
import { FaBridgeWater, FaMagnifyingGlass, FaPlus } from 'react-icons/fa6';
import { AiOutlineClear } from 'react-icons/ai';
import { GiForest, GiStoneBlock, GiDungeonGate } from 'react-icons/gi';
import { FaFlagCheckered } from 'react-icons/fa';
import { HiZoomIn, HiZoomOut } from 'react-icons/hi';
import { GoSync } from 'react-icons/go';
import { IoMdCreate } from 'react-icons/io';
import { RxHamburgerMenu, RxDotsHorizontal } from 'react-icons/rx';

export { BsTrash as Delete };
export { RxHamburgerMenu as Menu };
export { IoHome as Home };
export { IoVolumeHigh as Volume };
export { IoVolumeMedium as Medium };
export { IoVolumeMuteSharp as Mute };
export { RiCheckboxBlankCircleLine as Check };
export { RiCheckboxCircleLine as Checked };
export { GrView as View };
export { GrPowerReset as Reset };
export { HiOutlineArrowLeft as Undo };
export { HiOutlineArrowRight as Redo };
export { BiSolidTree as Tree };
export { GiForest as Trees };
export { AiOutlineClear as Clear };
export { FaBridgeWater as Bridge };
export { BsWater as Water };
export { GiStoneBlock as Rock };
export { FaFlagCheckered as Start };
export { HiZoomIn as Zoomin };
export { HiZoomOut as Zoomout };
export { GiDungeonGate as Gate };
export { BsHexagonFill as Hex };
export { RiLandscapeFill as Map };
export { GoSync as Reload };
export { IoMdCreate as Craft };
export { FaMagnifyingGlass as Zoom };
export { RxDotsHorizontal as Actions };
export { FaPlus as Plus };
