import { BsArrowRight, BsArrowLeft, BsArrowDownLeft, BsArrowDownRight, BsArrowUpLeft, BsArrowUpRight, BsArrowUp, BsArrowDown } from 'react-icons/bs';
import { GiForest, GiStoneBlock, GiDungeonGate, GiRiver, GiFallingLeaf, GiGrass, GiHorizonRoad, GiHouse } from 'react-icons/gi';
import { IoVolumeHigh, IoVolumeMuteSharp, IoVolumeMedium, IoHome, IoStopOutline } from 'react-icons/io5';
import { RiCheckboxBlankCircleLine, RiCheckboxCircleLine, RiLandscapeFill } from 'react-icons/ri';
import { FaBridgeWater, FaMagnifyingGlass, FaPlus, FaRegCircleQuestion } from 'react-icons/fa6';
import { HiOutlineArrowLeft, HiOutlineArrowRight } from 'react-icons/hi2';
import { RxHamburgerMenu, RxDotsHorizontal, RxCross2 } from 'react-icons/rx';
import { BsTrash, BsWater, BsHexagonFill } from 'react-icons/bs';
import { FaFlagCheckered, FaCog, FaEye } from 'react-icons/fa';
import { GrView, GrPowerReset } from 'react-icons/gr';
import { HiZoomIn, HiZoomOut } from 'react-icons/hi';
import { PiExport, PiPlay } from 'react-icons/pi';
import { AiOutlineClear } from 'react-icons/ai';
import { BiSolidTree } from 'react-icons/bi';
import { IoMdCreate } from 'react-icons/io';
import { GoSync } from 'react-icons/go';

export { FaRegCircleQuestion as Unknown };

export { RiCheckboxBlankCircleLine as Check };
export { RiCheckboxCircleLine as Checked };
export { HiOutlineArrowRight as Redo };
export { RxDotsHorizontal as Actions };
export { HiOutlineArrowLeft as Undo };
export { IoVolumeMuteSharp as Mute };
export { FaMagnifyingGlass as Zoom };
export { GiFallingLeaf as Clearing };
export { FaFlagCheckered as Start };
export { IoVolumeMedium as Medium };
export { RxHamburgerMenu as Menu };
export { AiOutlineClear as Clear };
export { FaBridgeWater as Bridge };
export { IoVolumeHigh as Volume };
export { RiLandscapeFill as Map };
export { GiDungeonGate as Gate };
export { GrPowerReset as Reset };
export { GiHorizonRoad as Road };
export { IoStopOutline as Stop };
export { GiStoneBlock as Rock };
export { BsHexagonFill as Hex };
export { HiZoomOut as Zoomout };
export { BiSolidTree as Tree };
export { IoMdCreate as Craft };
export { PiExport as Export };
export { HiZoomIn as Zoomin };
export { GiForest as Trees };
export { BsTrash as Delete };
export { FaCog as Settings };
export { RxCross2 as Erase };
export { BsWater as Water };
export { GoSync as Reload };
export { GiRiver as Shore };
export { GiGrass as Grass };
export { GiHouse as House };
export { FaEye as Preview };
export { PiPlay as Play };
export { IoHome as Home };
export { GrView as View };
export { FaPlus as Plus };

export { BsArrowDownRight as Bottom_right };
export { BsArrowDownLeft as Bottom_left };
export { BsArrowUpRight as Top_right };
export { BsArrowUpLeft as Top_left };
export { BsArrowDown as Bottom };
export { BsArrowRight as Right };
export { BsArrowLeft as Left };
export { BsArrowUp as Top };
